def div42(f) {
    try {
        f()
    }
    .catch {
        case Some { value }:
            resume x
        case None:
            resume 42
    }
}

def main() {
    div42 {
        5 / 0
    }
}

class DivideZeroError {
    numerator: int
}



def safe_div(numerator: int, denominator: int) -> int / DivideZeroError {
if denominator == 0 {
raise new Failure[int, DivZeroError] {
error: DivZeroError {
numerator
}
}
}
else {
numerator.div_ceil(denominator)
}
}

